# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\x1e\n\rCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\"!\n\x0e\x43reateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05title\x18\x01 \x01(\t\"*\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe3\x01\n\x0bTodoService\x12\x35\n\x06\x43reate\x12\x13.todo.CreateRequest\x1a\x14.todo.CreateResponse\"\x00\x12/\n\x04Read\x12\x11.todo.ReadRequest\x1a\x12.todo.ReadResponse\"\x00\x12\x35\n\x06Update\x12\x13.todo.UpdateRequest\x1a\x14.todo.UpdateResponse\"\x00\x12\x35\n\x06\x44\x65lete\x12\x13.todo.DeleteRequest\x1a\x14.todo.DeleteResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUEST._serialized_start=20
  _CREATEREQUEST._serialized_end=50
  _CREATERESPONSE._serialized_start=52
  _CREATERESPONSE._serialized_end=85
  _READREQUEST._serialized_start=87
  _READREQUEST._serialized_end=112
  _READRESPONSE._serialized_start=114
  _READRESPONSE._serialized_end=143
  _UPDATEREQUEST._serialized_start=145
  _UPDATEREQUEST._serialized_end=187
  _UPDATERESPONSE._serialized_start=189
  _UPDATERESPONSE._serialized_end=222
  _DELETEREQUEST._serialized_start=224
  _DELETEREQUEST._serialized_end=251
  _DELETERESPONSE._serialized_start=253
  _DELETERESPONSE._serialized_end=286
  _TODOSERVICE._serialized_start=289
  _TODOSERVICE._serialized_end=516
# @@protoc_insertion_point(module_scope)
